/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <list>
#include <iostream>

using namespace std;

class person {
public:
    //初始化参数表
    person(string name, int sex) : name_(name), sex_(sex) {

    }

    //get成员方法
    string get_name() {
        return name_;
    }

    int get_sex() {
        return sex_;
    }

    string get_sex_name() {
        string name = "unknown";
        if (sex_ == 1) {
            name = "男";
        } else if (sex_ == 2) {
            name = "女";
        }
        return name;
    }

    string get_log_info() {
        return "[打印信息] [姓名]" + get_name() + "，[性别]" + get_sex_name()
               + "\n[性别代码]" + to_string(sex_);
    }

private:
    string name_;
    int  sex_;
};

class log_util {
public:
    void d(string message) {
        cout << message << endl;
    }
};

extern "C" {

/*
 * Class:     com_unistrong_demo_Sample1
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_unistrong_demo_Sample1_stringMethod
        (JNIEnv *env, jobject) {
    string src = "this is cpp text";

    //第5个元素
    char char_at_5 = src.at(0);
    //去除空格
    string string_buffer;
    int index;
    for (index = 0; index < src.length(); index++) {
        char character = src.at(index);
        if (' ' != character) {
            string_buffer.append(&character);
        }
    }

    //构造类
    person zhangsan("zhangsan", 1);
    person jinlian("jinlian", 2);
    string result = zhangsan.get_log_info() + "\n" + jinlian.get_log_info();

    //return env->NewStringUTF(string_buffer.c_str());//src.c_str()
    return env->NewStringUTF(result.c_str());//src.c_str()
}


//JNIEXPORT jint JNICALL Java_com_unistrong_demo_Sample1_intMethod
//        (JNIEnv *env, jclass ) {
//    return env->(5);
//}

}


